In [22]:
import numpy as np

In [23]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0] 
bias = 2

output = inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + inputs[3] * weights[3] + bias
output

4.8

In [24]:
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2, 3, 0.5]

np.dot(weights, inputs) + biases


array([4.8  , 1.21 , 2.385])

In [25]:
np.array([1, 2]) * [3, 4]

array([3, 8])

In [28]:
inputs = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

np.dot(inputs, np.array(weights).T) + biases

array([[ 2.8  , -1.79 ,  1.885],
       [ 6.9  , -4.81 , -0.3  ],
       [-0.59 , -1.949, -0.474]])

In [30]:
weights2 = [
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]
]

biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2
layer2_outputs

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [49]:
np.random.seed(0)
X = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

class Layer_Dense:
    def  __init__(self, n_inputs, n_neurons) -> None:
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(
    len(X[0]), # 4
    7)
layer1.forward(X)
layer1.output


layer2 = Layer_Dense(
    7,
    2)
layer2.forward(layer1.output)
layer2.output

array([[0.11301128, 0.13112925],
       [0.05034201, 0.07345577],
       [0.07660713, 0.02734106]])

In [43]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])